export const SHIPPING_ADDRESS_DETAILS_REQUEST = 'SHIPPING_ADDRESS_DETAILS_REQUEST';
export const SHIPPING_ADDRESS_DETAILS_SUCCESS = 'SHIPPING_ADDRESS_DETAILS_SUCCESS';
export const SHIPPING_ADDRESS_DETAILS_FAIL = 'SHIPPING_ADDRESS_DETAILS_FAIL';
export const SHIPPING_ADDRESS_DETAILS_RESET = 'SHIPPING_ADDRESS_DETAILS_RESET';

export const SHIPPING_ADDRESS_CREATE_REQUEST = 'SHIPPING_ADDRESS_CREATE_REQUEST';
export const SHIPPING_ADDRESS_CREATE_SUCCESS = 'SHIPPING_ADDRESS_CREATE_SUCCESS';
export const SHIPPING_ADDRESS_CREATE_FAIL = 'SHIPPING_ADDRESS_CREATE_FAIL';
export const SHIPPING_ADDRESS_CREATE_RESET = 'SHIPPING_ADDRESS_CREATE_RESET';

export const SHIPPING_ADDRESS_UPDATE_REQUEST = 'SHIPPING_ADDRESS_UPDATE_REQUEST';
export const SHIPPING_ADDRESS_UPDATE_SUCCESS = 'SHIPPING_ADDRESS_UPDATE_SUCCESS';
export const SHIPPING_ADDRESS_UPDATE_FAIL = 'SHIPPING_ADDRESS_UPDATE_FAIL';
export const SHIPPING_ADDRESS_UPDATE_RESET = 'SHIPPING_ADDRESS_UPDATE_RESET';

export const SHIPPING_ADDRESS_LIST_REQUEST = 'SHIPPING_ADDRESS_LIST_REQUEST';
export const SHIPPING_ADDRESS_LIST_SUCCESS = 'SHIPPING_ADDRESS_LIST_SUCCESS';
export const SHIPPING_ADDRESS_LIST_FAIL = 'SHIPPING_ADDRESS_LIST_FAIL';